const day = 'вася'
if (day === 'четверг')
    console.log(`${day} является 4 днем недели`)
else if (day === 'понедельник')
    console.log(`${day} является 1 днем недели`)
else if (day === 'вторник')
    console.log(`${day} является 2 днем недели`)
else if (day === 'среда')
    console.log(`${day} является 3 днем недели`)
else if (day === 'пятница')
    console.log(`${day} является 5 днем недели`)
else if(day === 'суббота')
    console.log(`${day} является 6 днем недели`)
else if(day === 'воскресенье')
    console.log(`${day} является 7 днем недели`)
else 
console.log('не правильно введены данные')